### ISSUE TITLE
"Device Flow must be explicitly enabled for this App"

### ISSUE THREAD

**Issue by platform-kit** [simoneb/ghenv#10]
```
❯ ghenv write
{"error":"device_flow_disabled","error_description":"Device Flow must be explicitly enabled for this App","error_uri":"https://docs.github.com"}
Error: Unable obtain a device code
```

As admin of the app, you need to tick this box:

https://github.blog/changelog/2022-03-16-enable-oauth-device-authentication-flow-for-apps/

**Comment by simoneb** [comment]
I changed the app settings, can you confirm that it's working fine now?
